// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteAdviceRun(arg1:number):Promise<void>;

export function GenerateAdviceComparison(arg1:string,arg2:string):Promise<model.AdviceRun>;

export function GetAdviceRuns(arg1:string,arg2:string,arg3:number):Promise<Array<model.AdviceRun>>;

export function GetAppVersion():Promise<string>;

export function GetBenchmarkComparison(arg1:string,arg2:string):Promise<model.BenchmarkComparison>;

export function GetBenchmarkPlayers(arg1:string,arg2:string):Promise<Array<model.BenchmarkPlayer>>;

export function GetFGCTrackerErrorModelUnused():Promise<model.FGCTrackerError>;

export function GetGuiConfig():Promise<model.GUIConfig>;

export function GetLatestAdviceRun(arg1:string,arg2:string):Promise<model.AdviceRun>;

export function GetLatestMatchForUserAndCharacter(arg1:string,arg2:string):Promise<model.Match>;

export function GetMatches(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<model.Match>>;

export function GetMatchesWithPlayStats(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<model.MatchWithStats>>;

export function GetPlayStatsCharacters(arg1:string):Promise<Array<string>>;

export function GetPlayStatsHistory(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<Array<model.PlayStatsSnapshot>>;

export function GetSF6CharacterMoves(arg1:string,arg2:string,arg3:number):Promise<Array<model.SF6CharacterMove>>;

export function GetSessions(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<model.Session>>;

export function GetSessionsStatistics(arg1:string):Promise<model.SessionsStatistics>;

export function GetSupportedLanguages():Promise<Array<string>>;

export function GetThemes():Promise<Array<model.Theme>>;

export function GetTranslation(arg1:string):Promise<model.Localization>;

export function GetUsers():Promise<Array<model.User>>;

export function OpenResultsDirectory():Promise<void>;

export function RefreshBenchmarkPlayers(arg1:string,arg2:string):Promise<Array<model.BenchmarkPlayer>>;

export function RefreshMissingMatchesNow():Promise<number>;

export function SaveAdviceFeedback(arg1:number,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number,arg7:string):Promise<void>;

export function SaveLocale(arg1:string):Promise<void>;

export function SaveSidebarMinimized(arg1:boolean):Promise<void>;

export function SaveTheme(arg1:model.ThemeName):Promise<void>;

export function SyncSF6CharacterData(arg1:string,arg2:string):Promise<Array<model.SF6CharacterMove>>;

export function SyncVegapunkGrowthData(arg1:string,arg2:string):Promise<void>;
